import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg:         "var(--bg)",
        "bg-card":  "var(--bg-card)",
        "bg-elev":  "var(--bg-elev)",
        "bg-inset": "var(--bg-inset)",
        fg:         "var(--fg)",
        "fg-muted": "var(--fg-muted)",
        "fg-dim":   "var(--fg-dim)",
        "fg-faint": "var(--fg-faint)",
        border:          "var(--border)",
        "border-bright": "var(--border-bright)",
        accent:         "var(--accent)",
        "accent-deep":  "var(--accent-deep)",
        "accent-muted": "var(--accent-muted)",
        "accent-glow":  "var(--accent-glow)",
        ok:   "var(--ok)",
        warn: "var(--warn)",
        err:  "var(--err)",
        parchment: "var(--parchment)",
        ash:       "var(--ash)",
        stone:     "var(--stone)",
        mute:      "var(--mute)",
        earth:     "var(--earth)",
        charcoal:  "var(--charcoal)",
        void:      "var(--void)",
        amber: {
          DEFAULT: "var(--amber)",
          deep:    "var(--amber-deep)",
          muted:   "var(--amber-muted)",
          glow:    "var(--amber-glow)",
        },
      },
      fontFamily: {
        sans:    ["var(--font-sans)"],
        mono:    ["var(--font-mono)"],
        display: ["var(--font-display)"],
      },
      fontSize: {
        micro:   ["var(--fs-micro)",   { lineHeight: "1.4" }],
        xs:      ["var(--fs-xs)",      { lineHeight: "1.4" }],
        sm:      ["var(--fs-sm)",      { lineHeight: "1.45" }],
        base:    ["var(--fs-base)",    { lineHeight: "1.45" }],
        md:      ["var(--fs-md)",      { lineHeight: "1.4" }],
        lg:      ["var(--fs-lg)",      { lineHeight: "1.3" }],
        xl:      ["var(--fs-xl)",      { lineHeight: "1.2" }],
        "2xl":   ["var(--fs-2xl)",     { lineHeight: "1.1" }],
        display: ["var(--fs-display)", { lineHeight: "1.0" }],
      },
      letterSpacing: {
        label:      "var(--label-tracking)",
        labelTight: "var(--label-tracking-tight)",
        tight:      "-0.02em",
        tighter:    "-0.03em",
      },
      spacing: {
        0: "var(--sp-0)",
        1: "var(--sp-1)",
        2: "var(--sp-2)",
        3: "var(--sp-3)",
        4: "var(--sp-4)",
        5: "var(--sp-5)",
        6: "var(--sp-6)",
        7: "var(--sp-7)",
        8: "var(--sp-8)",
        9: "var(--sp-9)",
      },
      borderRadius: {
        sm:   "var(--r-sm)",
        md:   "var(--r-md)",
        lg:   "var(--r-lg)",
        xl:   "var(--r-xl)",
        pill: "var(--r-pill)",
      },
      boxShadow: {
        soft:  "var(--shadow-soft)",
        lift:  "var(--shadow-lift)",
        modal: "var(--shadow-modal)",
        inset: "var(--shadow-inset)",
      },
      transitionTimingFunction: {
        out:    "var(--ease-out)",
        spring: "var(--ease-spring)",
      },
      transitionDuration: {
        fast: "var(--dur-fast)",
        base: "var(--dur-base)",
        slow: "var(--dur-slow)",
      },
      zIndex: {
        nav:    "var(--z-nav)",
        sticky: "var(--z-sticky)",
        modal:  "var(--z-modal)",
        toast:  "var(--z-toast)",
      },
      keyframes: {
        fadeUp:    { from: { opacity: "0", transform: "translateY(8px)" },
                     to:   { opacity: "1", transform: "none" } },
        fadeIn:    { from: { opacity: "0" }, to: { opacity: "1" } },
        pulseSoft: { "0%,100%": { opacity: "0.6" }, "50%": { opacity: "1" } },
        tick:      { "0%,100%": { transform: "scaleY(0.4)" }, "50%": { transform: "scaleY(1)" } },
        shimmer:   { "0%": { backgroundPosition: "-200% 0" },
                     "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        fadeUp:    "fadeUp 420ms var(--ease-out) both",
        fadeIn:    "fadeIn 300ms ease both",
        pulseSoft: "pulseSoft 1.8s ease-in-out infinite",
        tick:      "tick 900ms ease-in-out infinite",
        shimmer:   "shimmer 2.4s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
