/**
 * Agent Run State Machine types
 *
 * Defines the discriminated union for run states, timeline segments,
 * and reducer actions that drive the ChatSurface redesign.
 *
 * See: BEHAVIOR.md §2 (state machine), SURFACE.md §3 (timeline)
 */

import type { Artifact } from "@/components/chat/ArtifactRenderer";

// =============================================================================
// Run State Machine (BEHAVIOR.md §2)
// =============================================================================

/** All possible phases of an agent run */
export type RunPhase =
  | "idle"
  | "submitted"
  | "thinking"
  | "streaming"
  | "executing"
  | "resuming"
  | "error";

/** Discriminated union for run state */
export type RunState =
  | { phase: "idle" }
  | { phase: "submitted"; startedAt: number }
  | { phase: "thinking"; runId: string; startedAt: number }
  | { phase: "streaming"; runId: string; messageId: string; startedAt: number }
  | { phase: "executing"; runId: string; toolCallId: string; toolName: string; startedAt: number }
  | { phase: "resuming"; runId: string; startedAt: number }
  | { phase: "error"; runId?: string; error: string };

// =============================================================================
// Timeline Segments (SURFACE.md §3.1)
// =============================================================================

/** A single step within an agent activity block */
export interface ActivityStep {
  toolCallId: string;
  toolName: string;
  args?: Record<string, unknown>;
  status: "running" | "complete" | "error";
  result?: {
    success: boolean;
    message?: string;
    error?: string;
    data?: Record<string, unknown>;
  };
  durationMs?: number;
  startedAt: number;
}

/** Base fields shared by all timeline segments */
interface SegmentBase {
  id: string;
  timestamp: number;
}

/** User's sent message */
export interface UserMessageSegment extends SegmentBase {
  type: "user-message";
  content: string;
  uploads?: { id: string; name: string; url?: string }[];
}

/** Agent's extended thinking / reasoning */
export interface AgentReasoningSegment extends SegmentBase {
  type: "agent-reasoning";
  content: string;
  isStreaming: boolean;
}

/** Agent activity block: grouped tool executions */
export interface AgentActivitySegment extends SegmentBase {
  type: "agent-activity";
  steps: ActivityStep[];
}

/** Agent's text response (may still be streaming) */
export interface AgentMessageSegment extends SegmentBase {
  type: "agent-message";
  messageId: string;
  content: string;
  isStreaming: boolean;
}

/** Work product: image, code, audio, 3D model, etc. */
export interface ArtifactSegment extends SegmentBase {
  type: "artifact";
  artifact: Artifact;
  toolCallId?: string;
}

/** Discriminated union of all timeline segment types */
export type TimelineSegment =
  | UserMessageSegment
  | AgentReasoningSegment
  | AgentActivitySegment
  | AgentMessageSegment
  | ArtifactSegment;

export type TimelineSegmentType = TimelineSegment["type"];

// =============================================================================
// Reducer Actions
// =============================================================================

export type RunAction =
  // User initiates
  | { type: "SUBMIT"; content: string; uploads?: UserMessageSegment["uploads"] }
  // Server lifecycle
  | { type: "RUN_STARTED"; runId: string; thinking?: boolean }
  | { type: "RUN_FINISHED"; runId: string; threadTitle?: string }
  | { type: "RUN_ERROR"; runId: string; error: string }
  // Reasoning / thinking
  | { type: "REASONING_START" }
  | { type: "REASONING_DELTA"; delta: string }
  | { type: "REASONING_END" }
  // Text streaming
  | { type: "TEXT_START"; messageId: string }
  | { type: "TEXT_DELTA"; delta: string }
  | { type: "TEXT_END" }
  // Tool execution
  | { type: "TOOL_START"; toolCallId: string; toolName: string }
  | { type: "TOOL_ARGS"; toolCallId: string; args: Record<string, unknown> }
  | { type: "TOOL_RESULT"; toolCallId: string; result: ActivityStep["result"]; durationMs?: number }
  // Artifacts
  | { type: "ARTIFACT_CREATED"; artifact: Artifact; toolCallId?: string }
  // External: load existing thread history
  | { type: "LOAD_HISTORY"; segments: TimelineSegment[] }
  // User stops the run
  | { type: "STOP" };

// =============================================================================
// Reducer State
// =============================================================================

export interface AgentRunState {
  runState: RunState;
  segments: TimelineSegment[];
  /** Title generated by the LLM for this thread (from RunFinished) */
  threadTitle?: string;
}

export const INITIAL_AGENT_RUN_STATE: AgentRunState = {
  runState: { phase: "idle" },
  segments: [],
};
